### PR TITLE
mention the necessary renaming of the downloads

### PR DESCRIPTION
**Pull request by nschlemm**
To prevent unnecessary duplicates of #149 ;)

### CODE REVIEW

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

Thanks @nschlemm, you are right. We may change how the unpacker works later, but for now updating the README like this is accurate.

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by fbriggs** [comment]
Doh.. nschlemm, I couldn't approve your pull request without a CLA on file. See the link above. If you prefer not to do that, we will sort it out eventually. Thanks.

**Comment by nschlemm** [comment]
@fbriggs I signed the (company) CLA before opening this PR, so it should be on file, or does that have to be approved manually?

**Comment by JoelMarcey** [comment]
Looks like your GitHub id was not added to the CLA, which is required. I can fix that manually.

**Comment by nschlemm** [comment]
@JoelMarcey THX!

oddly enough, the github handle was printed just fine on the confirmation page ...

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by fbriggs** [comment]
Thanks for jumping on this Joel.

**Comment by nschlemm** [comment]
thanks guys!

@fbriggs are there specific plans to change the unpacker already?

**Comment by fbriggs** [comment]
yes

**Pull request closed without merging**
