### PR TITLE
3d ==> 3D in README

### PR DESCRIPTION
**Pull request by JoelMarcey**

### CODE REVIEW

**Comment by fbriggs** [comment]
@facebook-github-bot import

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1038335946262039/int_phab) to review internal test results.

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1038335946262039/int_phab) to review internal test results.

**Comment by JoelMarcey** [comment]
Trying with a new one.

**Pull request closed without merging**
