### PR TITLE
Update CALIBRATION.md

### PR DESCRIPTION
**Pull request by vensuka**
Error in the intrinsic_checkerboard.png location.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1073652229392693/int_phab) to review internal test results.

**Pull request closed without merging**
