### PR TITLE
Make license files and directory code font

### PR DESCRIPTION
**Pull request by JoelMarcey**
For easier visibility

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @fbriggs to be a potential reviewer.

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/504116836446295/int_phab) to review internal test results.

**Pull request closed without merging**
