### PR TITLE
Add RGGB bayer support for Halide

### PR DESCRIPTION
**Pull request by dangsiper**
The original halide code only support GBRG bayer.

This commit add support for RGGB bayer based on ```cam_to_isp_config_file``` param.

### CODE REVIEW

**Comment by dangsiper** [comment]
So far this commit can work good for accelerate param, but has some problem with fast param.
We'll fix it as soon as possible.

**Comment by dangsiper** [comment]
This submission‘s issue has been fixed.
Now it can work well with ```accelerate``` and ```fast``` to process GBRG/RGGB  bayer pictures.
Please help to review this submission.

**Comment by aparrapo** [comment]
Thanks @dangsiper for the diff. I tested it and everything works fine :)

**Comment by dangsiper** [comment]
It's my pleasure, @aparrapo @bkcabral

**Pull request closed without merging**
