### PR TITLE
judge avfilter arrary's element

### PR DESCRIPTION
**Pull request by dangsiper**
judge the arrary's element

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @fbriggs and @aparrapo to be potential reviewers.

**Comment by aparrapo** [comment]
@dangsiper: I had to revert this pull due to some sync issues, but I'll put things back when it's resolved :)

**Comment by aparrapo** [comment]
@dangsiper: in order to acknowledge your contribution, we'd like you to please submit the same pull request again, instead of us doing it internally. Thanks and sorry for the inconvenience! :)

**Comment by dangsiper** [comment]
Dear @aparrapo 
I have submit the same pull request again(https://github.com/facebook/Surround360/pull/103), please help me to merge it at your convenience.
Thanks.

**Pull request merged**
