### PR TITLE
preview URL not match

### PR DESCRIPTION
**Pull request by dangsiper**
"camera_control/CameraControl.cpp" and "www/camera_capture/index.php"'s preview URL are not match.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @aparrapo to be a potential reviewer.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by dangsiper** [comment]
I signed up CLA just now.
Please review this commit at your convenient time.
Thanks.

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by aparrapo** [comment]
preview.ffm and live.webm are referring to different things. They are defined in:

https://github.com/facebook/Surround360/blob/master/surround360_camera_ctl/configs/ffserver.conf

**Pull request closed without merging**
