### PR TITLE
Updated Contributing guideline for correct visualization in Github

### PR DESCRIPTION
**Pull request by chaicko**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fbriggs** [comment]
Hi chaicko, thanks for submitting a patch. This is my first open source project at Facebook, and I am still learning the process for how we synchronize github patches with our internal facebook repository. Here we go...

@facebook-github-bot import

**Comment by fbriggs** [comment]
@facebook-github-bot import

**Comment by fbriggs** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1107486752658840/int_phab) to review internal test results.

**Comment by fbriggs** [comment]
Hello again chaicko. We got synchronization issues sorted out on our end. Would you mind fixing merge conflicts and submitting an update? This is our standard policy with regard to accepting diffs from external developers. Your contribution is appreciated.

**Comment by chaicko** [comment]
@fbriggs Yes no problem, I'll take a look.

**Comment by chaicko** [comment]
@fbriggs just fixed

**Comment by fbriggs** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1107486752658840/int_phab) to review internal test results.

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1107486752658840/int_phab) to review internal test results.

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1107486752658840/int_phab) to review internal test results.

**Comment by fbriggs** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1107486752658840/int_phab) to review internal test results.

**Pull request closed without merging**
